"""baseline + admin enum + solicitacoes_vinculo

Revision ID: 93af7dca04e7
Revises: 
Create Date: 2026-08-30 15:45:38.058788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93af7dca04e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE tipo_usuario ADD VALUE IF NOT EXISTS 'admin'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favoritos_id'), table_name='favoritos')
    op.drop_table('favoritos')
    op.drop_table('etapas_edital')
    op.drop_index(op.f('ix_subareas_avaliacao_id'), table_name='subareas_avaliacao')
    op.drop_table('subareas_avaliacao')
    op.drop_index(op.f('ix_etapas_seletivo_id'), table_name='etapas_seletivo')
    op.drop_table('etapas_seletivo')
    op.drop_index(op.f('ix_seletivos_id'), table_name='seletivos')
    op.drop_table('seletivos')
    op.drop_index(op.f('ix_documentos_edital_id'), table_name='documentos_edital')
    op.drop_table('documentos_edital')
    op.drop_index(op.f('ix_tokens_recuperacao_id'), table_name='tokens_recuperacao')
    op.drop_table('tokens_recuperacao')
    op.alter_column('areas_avaliacao', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('areas_avaliacao_grande_area_id_fkey'), 'areas_avaliacao', type_='foreignkey')
    op.drop_column('areas_avaliacao', 'grande_area_id')
    op.drop_index(op.f('idx_areas_conhecimento_avaliacao'), table_name='areas_conhecimento')
    op.alter_column('coordenadores', 'email_institucional',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('coordenadores', 'instituicao_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('coordenadores', 'area_avaliacao_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('coordenadores', 'area_conhecimento_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('idx_editais_programa'), table_name='editais')
    op.drop_column('editais', 'arquivo_pdf_url')
    op.alter_column('estudantes', 'titulacao_atual',
           existing_type=sa.VARCHAR(length=50),
           type_=sa.Enum('Graduação', 'Especialização', 'Mestrado', 'Doutorado', name='titulacao'),
           postgresql_using='titulacao_atual::titulacao',
           existing_nullable=True)
    op.alter_column('instituicoes', 'nome',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_index(op.f('idx_notificacoes_estudante_lida'), table_name='notificacoes')
    op.alter_column('programas', 'coordenador_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('programas', 'id_capes',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index(op.f('idx_programas_area_avaliacao'), table_name='programas')
    op.drop_index(op.f('idx_programas_area_conhecimento'), table_name='programas')
    op.drop_index(op.f('idx_programas_coordenador'), table_name='programas')
    op.drop_constraint(op.f('programas_instituicao_id_nome_nivel_key'), 'programas', type_='unique')
    op.create_unique_constraint('uq_programa_inst_nome_nivel', 'programas', ['instituicao_id', 'nome', 'nivel'])
    op.create_unique_constraint(None, 'programas', ['id_capes'])
    op.create_check_constraint('ck_nota_capes', 'programas', 'nota_capes BETWEEN 1 AND 7')
    op.drop_column('programas', 'aceitando_candidaturas')
    op.drop_column('programas', 'nome_ingles')
    op.drop_index(op.f('idx_favoritos_estudante'), table_name='programas_favoritos')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_favoritos_estudante'), 'programas_favoritos', ['estudante_id'], unique=False)
    op.add_column('programas', sa.Column('nome_ingles', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('programas', sa.Column('aceitando_candidaturas', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_constraint('ck_nota_capes', 'programas', type_='check')
    op.drop_constraint(None, 'programas', type_='unique')
    op.drop_constraint('uq_programa_inst_nome_nivel', 'programas', type_='unique')
    op.create_unique_constraint(op.f('programas_instituicao_id_nome_nivel_key'), 'programas', ['instituicao_id', 'nome', 'nivel'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_programas_coordenador'), 'programas', ['coordenador_id'], unique=False)
    op.create_index(op.f('idx_programas_area_conhecimento'), 'programas', ['area_conhecimento_id'], unique=False)
    op.create_index(op.f('idx_programas_area_avaliacao'), 'programas', ['area_avaliacao_id'], unique=False)
    op.alter_column('programas', 'id_capes',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('programas', 'coordenador_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('idx_notificacoes_estudante_lida'), 'notificacoes', ['estudante_id', 'lida'], unique=False)
    op.alter_column('instituicoes', 'nome',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('estudantes', 'titulacao_atual',
               existing_type=sa.Enum('Graduação', 'Especialização', 'Mestrado', 'Doutorado', name='titulacao'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.add_column('editais', sa.Column('arquivo_pdf_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_editais_programa'), 'editais', ['programa_id', sa.literal_column('criado_em DESC')], unique=False)
    op.alter_column('coordenadores', 'area_conhecimento_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('coordenadores', 'area_avaliacao_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('coordenadores', 'instituicao_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('coordenadores', 'email_institucional',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.create_index(op.f('idx_areas_conhecimento_avaliacao'), 'areas_conhecimento', ['area_avaliacao_id'], unique=False)
    op.add_column('areas_avaliacao', sa.Column('grande_area_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('areas_avaliacao_grande_area_id_fkey'), 'areas_avaliacao', 'grandes_areas', ['grande_area_id'], ['id'])
    op.alter_column('areas_avaliacao', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('etapas_seletivo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seletivo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ordem', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['seletivo_id'], ['seletivos.id'], name=op.f('etapas_seletivo_seletivo_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('etapas_seletivo_pkey'))
    )
    op.create_index(op.f('ix_etapas_seletivo_id'), 'etapas_seletivo', ['id'], unique=False)
    op.create_table('tokens_recuperacao',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('usado', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('expira_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('tokens_recuperacao_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tokens_recuperacao_pkey')),
    sa.UniqueConstraint('token', name=op.f('tokens_recuperacao_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_tokens_recuperacao_id'), 'tokens_recuperacao', ['id'], unique=False)
    op.create_table('documentos_edital',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('edital_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('url_arquivo', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('url_externo', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_pdf', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['edital_id'], ['editais.id'], name=op.f('documentos_edital_edital_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('documentos_edital_pkey'))
    )
    op.create_index(op.f('ix_documentos_edital_id'), 'documentos_edital', ['id'], unique=False)
    op.create_table('seletivos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('area', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('subarea', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('nivel', postgresql.ENUM('MA', 'MP', 'D', name='nivelenum'), autoincrement=False, nullable=True),
    sa.Column('vagas', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nota_capes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('favoritados', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('link_inscricao', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('data_inicio', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('data_fim', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('data_prova', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('coordenador_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['coordenador_id'], ['usuarios.id'], name=op.f('seletivos_coordenador_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('seletivos_pkey'))
    )
    op.create_index(op.f('ix_seletivos_id'), 'seletivos', ['id'], unique=False)
    op.create_table('subareas_avaliacao',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_sucupira', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('area_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas_avaliacao.id'], name=op.f('subareas_avaliacao_area_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('subareas_avaliacao_pkey')),
    sa.UniqueConstraint('id_sucupira', name=op.f('subareas_avaliacao_id_sucupira_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_subareas_avaliacao_id'), 'subareas_avaliacao', ['id'], unique=False)
    op.create_table('etapas_edital',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('edital_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('data_etapa', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('ordem', sa.SMALLINT(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['edital_id'], ['editais.id'], name=op.f('etapas_edital_edital_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('etapas_edital_pkey'))
    )
    op.create_table('favoritos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('seletivo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['seletivo_id'], ['seletivos.id'], name=op.f('favoritos_seletivo_id_fkey')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('favoritos_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('favoritos_pkey'))
    )
    op.create_index(op.f('ix_favoritos_id'), 'favoritos', ['id'], unique=False)
    # ### end Alembic commands ###
