"""add solicitacoes_vinculo table

Revision ID: 967bce219871
Revises: 93af7dca04e7
Create Date: 2026-08-30 18:52:25.855780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '967bce219871'
down_revision: Union[str, Sequence[str], None] = '93af7dca04e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacoes_vinculo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('programa_id', sa.Integer(), nullable=False),
    sa.Column('coordenador_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'aprovado', 'rejeitado', name='status_solicitacao_vinculo'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('decidido_em', sa.DateTime(), nullable=True),
    sa.Column('decidido_por', sa.UUID(), nullable=True),
    sa.Column('motivo_rejeicao', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['coordenador_id'], ['coordenadores.usuario_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decidido_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['programa_id'], ['programas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programa_id', 'coordenador_id', name='uq_solicitacao_programa_coordenador')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitacoes_vinculo')
    # ### end Alembic commands ###
