"""add rascunho fields to solicitacoes_vinculo

Revision ID: af5fe33a1ff3
Revises: 967bce219871
Create Date: 2026-09-07 18:56:31.723607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af5fe33a1ff3'
down_revision: Union[str, Sequence[str], None] = '967bce219871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitacoes_vinculo', sa.Column('linhas_pesquisa_rascunho', sa.JSON(), nullable=True))
    op.add_column('solicitacoes_vinculo', sa.Column('etapas_processo_rascunho', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitacoes_vinculo', 'etapas_processo_rascunho')
    op.drop_column('solicitacoes_vinculo', 'linhas_pesquisa_rascunho')
    # ### end Alembic commands ###
